name: Pull posting submodule

on:
    workflow_dispatch:

permissions:
  contents: write
  pages: write
  id-token: write

concurrency:
  group: "pages"

defaults:
  run:
    shell: bash

jobs:
    update-submodule:
        runs-on: ubuntu-latest
        permissions:
            contents: write
            pull-requests: write
        steps:
            - name: Checkout
              uses: actions/checkout@v4
        
            - name: Checkout tools repo
              uses: actions/checkout@v4
              with:
                repository: yokikim/postTest
                path: content
              env:
                GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
            - name: install Git
              run: |
                sudo snap install git
            - name: Authorize Git
              run: |
                git config --global user.email "$GITHUB_ACTOR@users.noreply.github.com"
                git config --global user.name "$GITHUB_ACTOR"
            - name: Update submodule
              run: |
                git submodule update  --init --recursive --remote -f
                env:
                GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
            - name: Commit changes
              run: |
                git commit -m "Update submodule to latest commit"
                git push origin main
                env:
                GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}